"""re-create-new-table-daily-company-metrocs

Revision ID: 03ac0e48bf76
Revises: b0748dde94c7
Create Date: 2025-12-07 17:52:36.965204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ac0e48bf76'
down_revision: Union[str, Sequence[str], None] = 'b0748dde94c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_company_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('highest_used_model', sa.String(), nullable=False),
    sa.Column('least_used_model', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'region', 'company_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_company_metrics')
    # ### end Alembic commands ###
