"""add-region-in-transaction

Revision ID: 1816f340ab3b
Revises: fec0d5a2c2b3
Create Date: 2025-12-04 20:13:59.738537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1816f340ab3b'
down_revision: Union[str, Sequence[str], None] = 'fec0d5a2c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'region')
    # ### end Alembic commands ###
