"""create-daily-metrics-table

Revision ID: 3b85e1d56c74
Revises: 69fc8e481d67
Create Date: 2025-12-03 14:33:38.367236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b85e1d56c74'
down_revision: Union[str, Sequence[str], None] = '69fc8e481d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('highest_model_used', sa.String(), nullable=False),
    sa.Column('avg_spending', sa.Float(), nullable=False),
    sa.Column('costliest_model', sa.String(), nullable=False),
    sa.Column('least_used_model', sa.String(), nullable=False),
    sa.Column('avg_token_consumption', sa.Float(), nullable=False),
    sa.Column('model_efficiency_ratio', sa.Float(), nullable=False),
    sa.Column('active_subscriber_utilization_rate', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'region')
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_metrics_region'), 'daily_metrics', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metrics_region'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
