"""create-daily-metrics-model-company-table

Revision ID: 5a5ee865f3a9
Revises: 3b85e1d56c74
Create Date: 2025-12-03 14:36:52.599723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5ee865f3a9'
down_revision: Union[str, Sequence[str], None] = '3b85e1d56c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_company_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'company_name')
    )
    op.create_table('daily_model_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'region', 'model_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_model_metrics')
    op.drop_table('daily_company_metrics')
    # ### end Alembic commands ###
