"""remove-model-eff-ratio

Revision ID: 6503e74211b7
Revises: e3f2cdc970cd
Create Date: 2025-12-07 15:04:12.586428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6503e74211b7'
down_revision: Union[str, Sequence[str], None] = 'e3f2cdc970cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_metrics', 'model_efficiency_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('model_efficiency_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
