"""create-transactions-table

Revision ID: 7161f007c81b
Revises: 53fa2a6d89b0
Create Date: 2025-12-03 13:56:30.879462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7161f007c81b'
down_revision: Union[str, Sequence[str], None] = '53fa2a6d89b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('rate_per_1k', sa.Float(), nullable=False),
    sa.Column('calculated_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_conversation_id'), 'transactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_transactions_model_name'), 'transactions', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_model_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_conversation_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
