"""add-more-metrics-column-onto-daily-company

Revision ID: 8c56c12a9251
Revises: c9506b3a95c3
Create Date: 2025-12-07 13:30:34.525611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c56c12a9251'
down_revision: Union[str, Sequence[str], None] = 'c9506b3a95c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_company_metrics', sa.Column('region', sa.String(), nullable=False))
    op.add_column('daily_company_metrics', sa.Column('highest_used_model', sa.String(), nullable=False))
    op.add_column('daily_company_metrics', sa.Column('least_used_model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_company_metrics', 'least_used_model')
    op.drop_column('daily_company_metrics', 'highest_used_model')
    op.drop_column('daily_company_metrics', 'region')
    # ### end Alembic commands ###
