"""remove-table

Revision ID: b0748dde94c7
Revises: 6503e74211b7
Create Date: 2025-12-07 17:52:04.168410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0748dde94c7'
down_revision: Union[str, Sequence[str], None] = '6503e74211b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_company_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_company_metrics',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conversation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('highest_used_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('least_used_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('date', 'company_name', name=op.f('daily_company_metrics_pkey'))
    )
    # ### end Alembic commands ###
