"""Add token_consumption to daily_model_metrics

Revision ID: c9506b3a95c3
Revises: 08705d07f238
Create Date: 2025-12-07 12:46:43.087593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9506b3a95c3'
down_revision: Union[str, Sequence[str], None] = '08705d07f238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value to handle existing rows
    op.add_column('daily_model_metrics', sa.Column('token_consumption', sa.Integer(), nullable=False, server_default='0'))
    # Remove the server default after column is added
    op.alter_column('daily_model_metrics', 'token_consumption', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_model_metrics', 'token_consumption')
    # ### end Alembic commands ###
