"""Add daily_active_users table and token fields to daily_metrics

Revision ID: ee895bb8a4e7
Revises: ff5e62c060c6
Create Date: 2025-12-04 07:38:58.252862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee895bb8a4e7'
down_revision: Union[str, Sequence[str], None] = 'ff5e62c060c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
