"""add-date-in-transaction

Revision ID: fec0d5a2c2b3
Revises: ee895bb8a4e7
Create Date: 2025-12-04 12:23:39.098637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec0d5a2c2b3'
down_revision: Union[str, Sequence[str], None] = 'ee895bb8a4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
