"""alter-daily-metric-table

Revision ID: ff5e62c060c6
Revises: e4a8a32e0c3d
Create Date: 2025-12-04 07:22:42.806874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5e62c060c6'
down_revision: Union[str, Sequence[str], None] = 'e4a8a32e0c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_active_users',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'region', 'user_id')
    )
    op.create_index(op.f('ix_daily_active_users_date'), 'daily_active_users', ['date'], unique=False)
    op.create_index(op.f('ix_daily_active_users_region'), 'daily_active_users', ['region'], unique=False)
    op.create_index(op.f('ix_daily_active_users_user_id'), 'daily_active_users', ['user_id'], unique=False)
    op.add_column('daily_metrics', sa.Column('total_prompt_tokens', sa.Integer(), nullable=False))
    op.add_column('daily_metrics', sa.Column('total_completion_tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_metrics', 'total_completion_tokens')
    op.drop_column('daily_metrics', 'total_prompt_tokens')
    op.drop_index(op.f('ix_daily_active_users_user_id'), table_name='daily_active_users')
    op.drop_index(op.f('ix_daily_active_users_region'), table_name='daily_active_users')
    op.drop_index(op.f('ix_daily_active_users_date'), table_name='daily_active_users')
    op.drop_table('daily_active_users')
    # ### end Alembic commands ###
